//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using EntidadesClases.ModelSicPro;
namespace ManejadorModelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sicproEntities : DbContext
    {
        public sicproEntities()
            : base("name=sicproEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<co_anticom> co_anticom { get; set; }
        public virtual DbSet<co_porcomi> co_porcomi { get; set; }
        public virtual DbSet<co_presprod> co_presprod { get; set; }
        public virtual DbSet<co_proycartera> co_proycartera { get; set; }
        public virtual DbSet<gr_acceso> gr_acceso { get; set; }
        public virtual DbSet<gr_cierreregistro> gr_cierreregistro { get; set; }
        public virtual DbSet<gr_compania> gr_compania { get; set; }
        public virtual DbSet<gr_componente> gr_componente { get; set; }
        public virtual DbSet<gr_contacto> gr_contacto { get; set; }
        public virtual DbSet<gr_direccion> gr_direccion { get; set; }
        public virtual DbSet<gr_parametro> gr_parametro { get; set; }
        public virtual DbSet<gr_pass> gr_pass { get; set; }
        public virtual DbSet<gr_persona> gr_persona { get; set; }
        public virtual DbSet<gr_tc> gr_tc { get; set; }
        public virtual DbSet<pr_anulada> pr_anulada { get; set; }
        public virtual DbSet<pr_calculo> pr_calculo { get; set; }
        public virtual DbSet<pr_cuotapoliza> pr_cuotapoliza { get; set; }
        public virtual DbSet<pr_devolucion> pr_devolucion { get; set; }
        public virtual DbSet<pr_excluida> pr_excluida { get; set; }
        public virtual DbSet<pr_formriesgo> pr_formriesgo { get; set; }
        public virtual DbSet<pr_grupo> pr_grupo { get; set; }
        public virtual DbSet<pr_liqrec> pr_liqrec { get; set; }
        public virtual DbSet<pr_numaplicas> pr_numaplicas { get; set; }
        public virtual DbSet<pr_pago> pr_pago { get; set; }
        public virtual DbSet<pr_poliza> pr_poliza { get; set; }
        public virtual DbSet<pr_polmov> pr_polmov { get; set; }
        public virtual DbSet<pr_producto> pr_producto { get; set; }
        public virtual DbSet<pr_recibo> pr_recibo { get; set; }
        public virtual DbSet<pr_riesgo> pr_riesgo { get; set; }
        public virtual DbSet<re_caso> re_caso { get; set; }
        public virtual DbSet<re_histcaso> re_histcaso { get; set; }
        public virtual DbSet<re_siniestro> re_siniestro { get; set; }
        public virtual DbSet<co_sueldo> co_sueldo { get; set; }
        public virtual DbSet<pr_pagocompania> pr_pagocompania { get; set; }
    }
}
