//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class co_presprod
    {
        public string mes_proy { get; set; }
        public string anio_proy { get; set; }
        public string id_percart { get; set; }
        public int id_suc { get; set; }
        public Nullable<decimal> monto_proy { get; set; }
        public Nullable<decimal> monto_cproy { get; set; }
    }
}
