//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class co_sueldo
    {
        public string id_persona { get; set; }
        public decimal mes_sueldo { get; set; }
        public decimal anio_sueldo { get; set; }
        public decimal dias { get; set; }
        public Nullable<decimal> basico_sueldo { get; set; }
        public Nullable<decimal> bono_anti { get; set; }
    }
}
