//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class gr_cierreregistro
    {
        public string mes { get; set; }
        public string anio { get; set; }
        public System.DateTime ini_reg { get; set; }
        public System.DateTime fin_reg { get; set; }
        public decimal tcambio { get; set; }
    }
}
