//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class gr_direccion
    {
        public long id_dir { get; set; }
        public string id_per { get; set; }
        public string direccion { get; set; }
        public double id_tpdir { get; set; }
        public string telf_dir { get; set; }
        public string int_dire { get; set; }
        public string telf_cel { get; set; }
        public string telf_fax { get; set; }
        public string email { get; set; }
        public string casilla { get; set; }
        public string web { get; set; }
        public decimal id_emis { get; set; }
    }
}
