//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class gr_pass
    {
        public string id_per { get; set; }
        public string clave { get; set; }
        public Nullable<bool> cambio { get; set; }
        public string login { get; set; }
        public Nullable<bool> logged { get; set; }
        public Nullable<decimal> id_rol { get; set; }
    
        public virtual gr_persona gr_persona { get; set; }
    }
}
