//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class gr_parametro
    {
        public long id_par { get; set; }
        public string columna { get; set; }
        public string desc_param { get; set; }
        public string abrev_param { get; set; }
        public Nullable<decimal> valor_param { get; set; }
    }
}
