//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class gr_tc
    {
        public System.DateTime fecha { get; set; }
        public long id_div { get; set; }
        public Nullable<decimal> tcambio { get; set; }
        public string TRIAL360 { get; set; }
    }
}
