//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class pr_anulada
    {
        public long id_poliza { get; set; }
        public long id_movimiento { get; set; }
        public decimal monto_anulada { get; set; }
        public decimal neta_anulada { get; set; }
        public decimal comision_anulada { get; set; }
        public Nullable<decimal> anulada_mes { get; set; }
        public Nullable<decimal> anulada_anio { get; set; }
        public string anulada_por { get; set; }
        public long id_anulada { get; set; }
        public string TRIAL360 { get; set; }
    }
}
