//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class pr_devolucion
    {
        public long id_poliza { get; set; }
        public long id_movimiento { get; set; }
        public long id_devolucion { get; set; }
        public decimal cuota_devolucion { get; set; }
        public Nullable<decimal> monto_devolucion { get; set; }
        public Nullable<decimal> neta_devolucion { get; set; }
        public Nullable<decimal> comision_devolucion { get; set; }
        public Nullable<decimal> comision_pc { get; set; }
        public string cheque { get; set; }
        public string devolucion_por { get; set; }
        public Nullable<decimal> saldo_devolucion { get; set; }
        public string banco { get; set; }
        public Nullable<decimal> comis_mes { get; set; }
        public Nullable<decimal> comis_anio { get; set; }
    }
}
