//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class pr_liqrec
    {
        public int id_liq { get; set; }
        public Nullable<System.DateTime> fc_liq { get; set; }
        public string id_perucb { get; set; }
        public Nullable<decimal> monto_liqs { get; set; }
        public Nullable<decimal> monto_liqb { get; set; }
        public decimal id_suc { get; set; }
        public string TRIAL360 { get; set; }
    }
}
