//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class pr_polmov
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pr_polmov()
        {
            this.pr_cuotapoliza = new HashSet<pr_cuotapoliza>();
            this.pr_devolucion = new HashSet<pr_devolucion>();
            this.pr_excluida = new HashSet<pr_excluida>();
            this.pr_numaplicas = new HashSet<pr_numaplicas>();
        }
    
        public long id_poliza { get; set; }
        public long id_movimiento { get; set; }
        public string id_perejec { get; set; }
        public System.DateTime fc_emision { get; set; }
        public System.DateTime fc_inivig { get; set; }
        public System.DateTime fc_finvig { get; set; }
        public decimal prima_bruta { get; set; }
        public Nullable<decimal> prima_neta { get; set; }
        public Nullable<decimal> por_comision { get; set; }
        public Nullable<decimal> comision { get; set; }
        public long id_div { get; set; }
        public bool tipo_cuota { get; set; }
        public double num_cuota { get; set; }
        public long id_clamov { get; set; }
        public string estado { get; set; }
        public long id_dir { get; set; }
        public System.DateTime fc_recepcion { get; set; }
        public string mat_aseg { get; set; }
        public System.DateTime fc_reg { get; set; }
        public string no_liquida { get; set; }
        public long id_mom { get; set; }
        public string TRIAL363 { get; set; }
    
        public virtual gr_direccion gr_direccion { get; set; }
        public virtual gr_persona gr_persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pr_cuotapoliza> pr_cuotapoliza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pr_devolucion> pr_devolucion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pr_excluida> pr_excluida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pr_numaplicas> pr_numaplicas { get; set; }
    }
}
