//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class pr_pago
    {
        public long id_pago { get; set; }
        public double id_poliza { get; set; }
        public long id_movimiento { get; set; }
        public Nullable<decimal> cuota { get; set; }
        public Nullable<long> id_recibo { get; set; }
        public Nullable<decimal> anio_recibo { get; set; }
        public Nullable<double> factura { get; set; }
        public Nullable<System.DateTime> fecha_factura { get; set; }
        public Nullable<decimal> monto_pago { get; set; }
        public Nullable<decimal> neta_pago { get; set; }
        public Nullable<decimal> comision_pago { get; set; }
        public Nullable<long> id_tpago { get; set; }
        public Nullable<decimal> monto_comis { get; set; }
        public string cheque_comis { get; set; }
        public Nullable<decimal> comis_mes { get; set; }
        public Nullable<decimal> comis_anio { get; set; }
        public string pago_por { get; set; }
        public Nullable<int> id_liq { get; set; }
        public string TRIAL360 { get; set; }
    
        public virtual gr_parametro gr_parametro { get; set; }
    }
}
