//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class pr_riesgo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pr_riesgo()
        {
            this.pr_calculo = new HashSet<pr_calculo>();
            this.pr_formriesgo = new HashSet<pr_formriesgo>();
        }
    
        public string id_riesgo { get; set; }
        public string cod_mod { get; set; }
        public string cod_ram { get; set; }
        public string cod_pol { get; set; }
        public string desc_riesgo { get; set; }
        public string cobertura { get; set; }
        public string TRIAL363 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pr_calculo> pr_calculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pr_formriesgo> pr_formriesgo { get; set; }
    }
}
