//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class re_caso
    {
        public decimal id_caso { get; set; }//ok
        public decimal anio_caso { get; set; }//ok
        public int id_sucur { get; set; }//ok
        public string id_perclie { get; set; }//ok
        public string id_perurc { get; set; }//ok
        public long id_poliza { get; set; }//ok
        public decimal aprox_caso { get; set; }//ok
        public double id_divaprox { get; set; }//ok
        public Nullable<decimal> pago_caso { get; set; }
        public decimal franq_caso { get; set; }
        public decimal indem_caso { get; set; }
        public string inspector_cia { get; set; }//ok
        public string atendido_por { get; set; }//ok
        public string atendido_en { get; set; }//ok
        public Nullable<System.DateTime> fc_reg { get; set; }
        public Nullable<double> id_recibo { get; set; }
        public Nullable<decimal> anio_recibo { get; set; }
    }
}
