//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class re_siniestro
    {
        public double id_caso { get; set; }
        public decimal anio { get; set; }
        public int id_sucur { get; set; }
        public System.DateTime fc_incidente { get; set; }
        public string denunciante { get; set; }
        public string reladenun { get; set; }
        public string mat_aseg { get; set; }
        public string lugar_siniestro { get; set; }
        public string circunstancia { get; set; }
        public Nullable<double> id_uniobj { get; set; }
        public string uniobj { get; set; }
        public Nullable<System.DateTime> fc_denuncia { get; set; }
        public string TRIAL363 { get; set; }
    }
}
