//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_pr_cias_resum
    {
        public string id_spvs { get; set; }
        public string id_per { get; set; }
        public decimal cf { get; set; }
        public string abrev_cia { get; set; }
        public string rubro { get; set; }
        public string nomraz { get; set; }
        public Nullable<long> id_sal { get; set; }
    }
}
