//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class vcb_anulaciones
    {
        public long id_poliza { get; set; }
        public Nullable<decimal> cuota_total_t { get; set; }
        public Nullable<decimal> cuota_neta_t { get; set; }
        public Nullable<decimal> cuota_comis_t { get; set; }
        public Nullable<decimal> cuota_pago_t { get; set; }
        public Nullable<decimal> monto_exclusion_t { get; set; }
        public Nullable<decimal> neta_exclusion_t { get; set; }
        public Nullable<decimal> comision_exclusion_t { get; set; }
        public Nullable<decimal> monto_devolucion_t { get; set; }
        public Nullable<decimal> cuotatotal_t { get; set; }
        public Nullable<decimal> cuotapago_t { get; set; }
        public Nullable<long> id_mom { get; set; }
    }
}
