//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class vcb_cuotasdias
    {
        public string id_per { get; set; }
        public string nomraz { get; set; }
        public string num_poliza { get; set; }
        public string no_liquida { get; set; }
        public string abrev_prod { get; set; }
        public string no_cuota { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public Nullable<decimal> cuota_total { get; set; }
        public Nullable<decimal> cuota_pago { get; set; }
        public string abrev_param { get; set; }
        public Nullable<int> dias { get; set; }
        public decimal monto_exclusion { get; set; }
        public decimal monto_devolucion { get; set; }
        public Nullable<decimal> monto_cuota { get; set; }
        public Nullable<decimal> monto_pagado { get; set; }
        public Nullable<long> id_suc { get; set; }
        public string id_percart { get; set; }
        public string cartera { get; set; }
        public string id_perejec { get; set; }
        public string id_spvs { get; set; }
        public string abrev_cia { get; set; }
        public Nullable<decimal> monto_pendiente { get; set; }
        public Nullable<long> id_gru { get; set; }
        public string grupo { get; set; }
        public long id_poliza { get; set; }
        public long id_movimiento { get; set; }
        public string mat_aseg { get; set; }
        public long id_mom { get; set; }
    }
}
