//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class vcb_pagoxcuota
    {
        public double id_poliza { get; set; }
        public long id_movimiento { get; set; }
        public Nullable<decimal> cuota { get; set; }
        public Nullable<decimal> monto_pago { get; set; }
        public Nullable<decimal> neta_pago { get; set; }
        public Nullable<decimal> comision_pago { get; set; }
    }
}
