//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class vcb_repcob5
    {
        public string id_per { get; set; }
        public string nomraz { get; set; }
        public Nullable<long> id_suc { get; set; }
        public string sucursal { get; set; }
        public long id_producto { get; set; }
        public string desc_prod { get; set; }
        public string abrev_prod { get; set; }
        public string id_spvs { get; set; }
        public string abrev_cia { get; set; }
        public string nomraz_cia { get; set; }
        public decimal id_gru { get; set; }
        public string desc_grupo { get; set; }
        public string num_poliza { get; set; }
        public long id_poliza { get; set; }
    }
}
