//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class vcm_comicobrada
    {
        public Nullable<decimal> mes { get; set; }
        public Nullable<decimal> anio { get; set; }
        public string id_riesgo { get; set; }
        public string cod_mod { get; set; }
        public string desc_riesgo { get; set; }
        public string id_spvs { get; set; }
        public string abrev_cia { get; set; }
        public string descriesgo { get; set; }
        public Nullable<decimal> prima_total { get; set; }
    }
}
