//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class vcm_liqcomiejec
    {
        public long id_poliza { get; set; }
        public string id_perclie { get; set; }
        public string cliente { get; set; }
        public string id_percart { get; set; }
        public string id_perejec { get; set; }
        public string ejecutivo { get; set; }
        public string cartera { get; set; }
        public string id_spvs { get; set; }
        public string cia { get; set; }
        public long id_producto { get; set; }
        public string abrev_prod { get; set; }
        public Nullable<decimal> monto_pago { get; set; }
        public Nullable<decimal> neta_pago { get; set; }
        public Nullable<decimal> cuota { get; set; }
        public string num_poliza { get; set; }
        public Nullable<System.DateTime> fecha_factura { get; set; }
        public decimal porcentaje { get; set; }
        public bool factura { get; set; }
        public Nullable<decimal> comision_pago { get; set; }
        public Nullable<decimal> comi_cart { get; set; }
        public Nullable<decimal> facturable { get; set; }
        public long id_div { get; set; }
        public Nullable<long> id_suc { get; set; }
        public string sucursal { get; set; }
    }
}
