//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class vcm_preascii1
    {
        public string id_spvs { get; set; }
        public Nullable<int> mes { get; set; }
        public Nullable<int> anio { get; set; }
        public string cod_mod { get; set; }
        public string cod_ram { get; set; }
        public string cod_pol { get; set; }
        public Nullable<decimal> prima_total { get; set; }
        public Nullable<decimal> comision_total { get; set; }
        public Nullable<System.DateTime> fin_registro { get; set; }
        public Nullable<decimal> tcambio { get; set; }
        public Nullable<long> id_suc { get; set; }
        public string sucursal { get; set; }
    }
}
