//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class vgr_comprol
    {
        public decimal id_com { get; set; }
        public decimal dep_com { get; set; }
        public decimal nivel { get; set; }
        public string desc_comp { get; set; }
        public string ayuda { get; set; }
        public string vinculo { get; set; }
        public string icono { get; set; }
        public bool toolb { get; set; }
        public string imgtoolb { get; set; }
        public long id_rol { get; set; }
    }
}
