//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class vpr_formriesgo
    {
        public string id_riesgo { get; set; }
        public string id_spvs { get; set; }
        public decimal comis_riesgo { get; set; }
        public Nullable<bool> opera { get; set; }
        public Nullable<decimal> evaluar { get; set; }
        public long id_producto { get; set; }
        public string desc_prod { get; set; }
        public string abrev_prod { get; set; }
        public Nullable<decimal> por_cred { get; set; }
        public Nullable<decimal> plus_neta { get; set; }
    }
}
