//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class vpr_polexcluvar1
    {
        public long id_poliza { get; set; }
        public string num_poliza { get; set; }
        public long id_producto { get; set; }
        public string id_spvs { get; set; }
        public Nullable<long> id_gru { get; set; }
        public Nullable<bool> clase_poliza { get; set; }
        public string id_percart { get; set; }
        public Nullable<decimal> prima_bruta { get; set; }
        public Nullable<decimal> prima_neta { get; set; }
        public Nullable<decimal> comision { get; set; }
        public long id_div { get; set; }
        public long id_dir { get; set; }
        public long id_mom { get; set; }
        public string id_perclie { get; set; }
        public string nomraz { get; set; }
        public Nullable<System.DateTime> fc_finvig { get; set; }
        public string no_liquida { get; set; }
        public string id_perejec { get; set; }
        public long id_movimiento { get; set; }
    }
}
