//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class vre_maxcaso
    {
        public Nullable<long> id_histcaso { get; set; }
        public decimal id_caso { get; set; }
        public decimal anio { get; set; }
        public int id_sucur { get; set; }
    }
}
