//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class vre_memo1
    {
        public string id_perclie { get; set; }
        public string nomraz { get; set; }
        public string desc_grupo { get; set; }
        public string direccion { get; set; }
        public string Tipo_direc { get; set; }
        public string num_poliza { get; set; }
        public string no_liquida { get; set; }
        public long id_poliza { get; set; }
        public long id_movimiento { get; set; }
        public string clasepoliza { get; set; }
        public System.DateTime fc_inivig { get; set; }
        public System.DateTime fc_finvig { get; set; }
        public System.DateTime fc_emision { get; set; }
        public System.DateTime fc_recepcion { get; set; }
        public string movimiento { get; set; }
        public string desc_producto { get; set; }
        public string cia_aseg { get; set; }
        public string ejecutivo { get; set; }
        public string mat_aseg { get; set; }
        public decimal prima_bruta { get; set; }
        public string tipocuota { get; set; }
        public string divisa { get; set; }
    }
}
