//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesClases.ModelSicPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class zrep
    {
        public long id_poliza { get; set; }
        public long id_movimiento { get; set; }
        public Nullable<decimal> cuotatotal { get; set; }
        public Nullable<decimal> cuotaneta { get; set; }
        public Nullable<decimal> cuotacomis { get; set; }
        public Nullable<decimal> cuotapago { get; set; }
        public Nullable<decimal> netapago { get; set; }
        public Nullable<decimal> comispago { get; set; }
    }
}
